name: chrislema
favicon: null
layout_spectrum: 0.41498631285503507
typography_spectrum: 0.10888117831200361
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fcbe00'
    - '#353945'
    - '#fdde7c'
    - '#84868d'
  brandStrength: 0.6875
  lightness: 0.16851027286611497
  saturation: 0.1978810599539429
  rhythmicContrast: 0.8347064014524221
purpose: []
