name: chrislema
favicon: null
layout_spectrum: 0.36143
typography_spectrum: 0.15561
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fcbe00'
    - '#353945'
    - '#fdde7c'
    - '#84868d'
  brandStrength: 0.8125
  lightness: 0.4375
  saturation: 0.625
  rhythmicContrast: 0.8347064014524221
purpose: []
